import { riskLabel } from './scoring.js'

const SEVERITY_RANK = { critical: 3, warning: 2, info: 1 }
const SEVERITY_ICON = { critical: '🔴', warning: '⚠', info: 'ℹ' }

// ---------------------------------------------------------------------------
// Download helper
// ---------------------------------------------------------------------------

export function triggerDownload(filename, content, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** FileReview[] sorted by riskScore descending */
function sortedFileReviews(fileReviews) {
  return [...fileReviews.values()].sort((a, b) => b.riskScore - a.riskScore)
}

/** Issues sorted: critical → warning → info, then by line number */
function sortedIssues(issues) {
  return [...issues].sort((a, b) => {
    const rankDiff = (SEVERITY_RANK[b.severity] ?? 0) - (SEVERITY_RANK[a.severity] ?? 0)
    return rankDiff !== 0 ? rankDiff : a.line - b.line
  })
}

/** Wrap a CSV field in double-quotes if it contains commas, quotes, or newlines */
function csvField(value) {
  const str = value == null ? '' : String(value)
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`
  }
  return str
}

// ---------------------------------------------------------------------------
// toMarkdown
// ---------------------------------------------------------------------------

/**
 * Produces a structured, GitHub-renderable Markdown report.
 *
 * @param {object}              diffReview  — result object from reviewDiff()
 * @param {Map<string,object>}  fileReviews — Map<filename, FileReview> from store
 * @param {object[]}            files       — FileDiff[] from store
 * @returns {string}
 */
export function toMarkdown(diffReview, fileReviews, files) {
  const {
    overallRisk,
    totalIssues,
    durationMs,
    totalTokens,
    commitMessage,
    suggestedTests,
  } = diffReview

  const { label: riskLbl } = riskLabel(overallRisk)
  const seconds  = durationMs ? (durationMs / 1000).toFixed(1) : '—'
  const tokStr   = totalTokens > 0 ? totalTokens.toLocaleString() + ' tokens' : ''
  const fileMeta = new Map(files.map((f) => [f.filename, f]))
  const lines    = []

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push('# Code Review Report')
  lines.push(`> Generated by WebGPU Code Reviewer · ${new Date().toISOString()}`)
  lines.push('')
  lines.push(
    `**Overall Risk:** ${overallRisk} — ${riskLbl}  ` +
    `**Files:** ${fileReviews.size}  ` +
    `**Issues:** ${totalIssues.critical} critical · ${totalIssues.warning} warnings · ${totalIssues.info} info`
  )
  if (seconds !== '—' || tokStr) {
    const meta = [seconds !== '—' ? `${seconds}s` : null, tokStr].filter(Boolean).join(' · ')
    lines.push(`**Duration:** ${meta}`)
  }
  lines.push('')
  lines.push('---')
  lines.push('')

  // ── Issues by file ───────────────────────────────────────────────────────
  lines.push('## Issues by File')
  lines.push('')

  for (const fr of sortedFileReviews(fileReviews)) {
    const meta     = fileMeta.get(fr.filename)
    const { label: fileLbl } = riskLabel(fr.riskScore)
    const issueWord = fr.mergedIssues.length === 1 ? 'issue' : 'issues'

    lines.push(
      `### \`${fr.filename}\` — Risk ${fr.riskScore} ${fileLbl} · ` +
      `${fr.mergedIssues.length} ${issueWord}`
    )
    lines.push('')

    if (meta) {
      lines.push(`*+${meta.additions} / −${meta.deletions} lines*`)
      lines.push('')
    }

    // Per-chunk summaries (one paragraph per chunk that has a summary)
    const summaries = (fr.chunks ?? []).map((c) => c.summary).filter(Boolean)
    if (summaries.length > 0) {
      summaries.forEach((s) => lines.push(s))
      lines.push('')
    }

    if (fr.mergedIssues.length === 0) {
      lines.push('_No issues found._')
      lines.push('')
      lines.push('---')
      lines.push('')
      continue
    }

    for (const issue of sortedIssues(fr.mergedIssues)) {
      const icon = SEVERITY_ICON[issue.severity] ?? '·'
      lines.push(
        `#### ${icon} ${issue.severity.toUpperCase()} — ${issue.category} (line ${issue.line})`
      )
      lines.push('')
      lines.push(issue.message)
      if (issue.suggestion) {
        lines.push('')
        lines.push(`> **Suggestion:** ${issue.suggestion}`)
      }
      lines.push('')
    }

    lines.push('---')
    lines.push('')
  }

  // ── Security findings table ──────────────────────────────────────────────
  const securityIssues = [...fileReviews.entries()].flatMap(([filename, fr]) =>
    fr.mergedIssues
      .filter((i) => i.category === 'security')
      .map((i) => ({ ...i, _filename: filename }))
  )

  if (securityIssues.length > 0) {
    lines.push('## Security Findings')
    lines.push('')
    lines.push('| Severity | File | Line | Message |')
    lines.push('|---|---|---|---|')
    for (const i of sortedIssues(securityIssues)) {
      // Escape pipe characters inside table cells
      const msg = i.message.replace(/\|/g, '\\|')
      lines.push(`| ${i.severity.toUpperCase()} | \`${i._filename}\` | ${i.line} | ${msg} |`)
    }
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  // ── Suggested commit message ─────────────────────────────────────────────
  if (commitMessage) {
    lines.push('## Suggested Commit Message')
    lines.push('')
    lines.push('```')
    lines.push(commitMessage)
    lines.push('```')
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  // ── Suggested tests ──────────────────────────────────────────────────────
  if (suggestedTests?.length > 0) {
    lines.push('## Suggested Tests')
    lines.push('')
    suggestedTests.forEach((t, i) => lines.push(`${i + 1}. ${t}`))
    lines.push('')
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// toCSV
// ---------------------------------------------------------------------------

/**
 * Flat CSV — one row per issue. Suitable for spreadsheet import or CI parsing.
 *
 * @param {Map<string,object>} fileReviews
 * @returns {string}
 */
export function toCSV(fileReviews) {
  const rows = [
    ['filename', 'line', 'severity', 'category', 'message', 'suggestion', 'foundBy']
      .map(csvField)
      .join(','),
  ]

  for (const fr of sortedFileReviews(fileReviews)) {
    for (const issue of sortedIssues(fr.mergedIssues)) {
      rows.push(
        [
          fr.filename,
          issue.line,
          issue.severity,
          issue.category,
          issue.message,
          issue.suggestion ?? '',
          issue.foundBy ?? '',
        ]
          .map(csvField)
          .join(',')
      )
    }
  }

  return rows.join('\n')
}

// ---------------------------------------------------------------------------
// toJSON
// ---------------------------------------------------------------------------

/**
 * Human-readable JSON export of the full review result.
 *
 * @param {object}              diffReview
 * @param {Map<string,object>}  fileReviews
 * @param {object[]}            files
 * @returns {string}
 */
export function toJSON(diffReview, fileReviews, files) {
  const fileMeta = new Map(files.map((f) => [f.filename, f]))

  const payload = {
    exportedAt:     new Date().toISOString(),
    overallRisk:    diffReview.overallRisk,
    totalIssues:    diffReview.totalIssues,
    durationMs:     diffReview.durationMs,
    totalTokens:    diffReview.totalTokens,
    commitMessage:  diffReview.commitMessage  ?? '',
    suggestedTests: diffReview.suggestedTests ?? [],
    files: sortedFileReviews(fileReviews).map((fr) => {
      const meta = fileMeta.get(fr.filename)
      return {
        filename:   fr.filename,
        status:     meta?.status     ?? 'modified',
        additions:  meta?.additions  ?? 0,
        deletions:  meta?.deletions  ?? 0,
        riskScore:  fr.riskScore,
        issueCount: fr.issueCount,
        issues: sortedIssues(fr.mergedIssues).map((i) => ({
          line:       i.line,
          severity:   i.severity,
          category:   i.category,
          message:    i.message,
          suggestion: i.suggestion ?? null,
          foundBy:    i.foundBy    ?? null,
        })),
      }
    }),
  }

  return JSON.stringify(payload, null, 2)
}
